sudo: required
services:
  - docker

before_install:
  - docker build -t nmc03/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nmc03/react-test npm test -- --coverage

after_success:
  - docker build -t nmc03/multi-client ./client
  - docker build -t nmc03/multi-nginx ./nginx
  - docker build -t nmc03/multi-server ./server
  - docker build -t nmc03/multi-worker ./worker
#Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Use those images and push onto docker hub
  - docker push nmc03/multi-client
  - docker push nmc03/multi-nginx
  - docker push nmc03/multi-server
  - docker push nmc03/multi-worker
