version: "3"
services:
  postgres:
    image: "postgres:latest"
    # environment:
    #   POSTGRES_DB: "db"
    #   POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  api: # HOSTNAME aka server, changed due to nginx conflict term 'server'
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: # anytime our application tries to access anything in the app directory in the container, except for the node_modules folder, it will be redirected to the server directory in COMPLEX_FIBONACCI
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client: #hostname
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker: #hostname
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx: #hostname
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
